config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :posts
  resources :hearts, only: :create

  root 'pages#welcome'

  get "/about" => "pages#about"
  get "/contact" => "pages#contact"

end

app/models/heart.rb
class Heart < ActiveRecord::Base
  belongs_to :post
  validates :post_id, presence: true
end

app/models/post.rb
class Post < ActiveRecord::Base
  has_many :hearts
  has_attached_file :image, :styles => { :large => "1000x1000", :medium => "400x400>", :thumb => "100x100>" }
  validates_attachment_content_type :image, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]
  
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/hearts_controller.rb
class HeartsController < ApplicationController
        def create
          @heart = Heart.new(heart_params)

         if @heart.save
           redirect_to @heart.post, notice: 'Hearted post!'
         else
           redirect_to root_url, notice: "Sorry, we couldn't create that heart."
          end  
        end
        
        private
            # Never trust parameters from the scary internet, only allow the white list through.
         def heart_params
           params.require(:heart).permit(:post_id)
          end
        end
      

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def contact
  end
  
  def welcome
    @posts = Post.all
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :content, :image)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>hobbolr</title>
  <link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap.min.css">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
   <meta name="viewport" content="initial-scale=1">
</head>
  
<body>
    <div class="container">
      <div class="header">
        <ul class="nav nav-pills pull-right">
          <li class="<%= 'active' if current_page?(root_path) %>"><%= link_to "Home", root_path %></li>        
        <li class="<%= 'active' if current_page?(about_path) %>"><%= link_to "About", about_url %></li>
            
            <% if user_signed_in? %>
              <li class="<%= 'active' if current_page?(posts_path) %>"><%= link_to "Manage", posts_url %></li>
              <li><%= link_to "Log out", destroy_user_session_path, method: :delete %></li>
            <% end %>
          
      </ul>
    
      <div class="page-header">
        <h1><a href="/">hobbolr</a> <small>// not tumblr</small></h1>
      </div>
     </div>
    </div>  
    

  <div class="row">
    <div class="col-xs-6 col-md-offset-3">
        <% if notice.present? %>
    <p class="alert alert-info"><%= notice %></p>
  <% end %>
    <p>
  
        <%= yield %>  
    </div>
  </div>

</body>
</html>

app/views/pages/about.html.erb
<h1>Pages#about</h1>
<p>Find me in app/views/pages/about.html.erb</p>

app/views/pages/contact.html.erb
<h1>Pages#contact</h1>
<p>Find me in app/views/pages/contact.html.erb</p>

app/views/pages/welcome.html.erb
<% @posts.reverse.each do |post| %>

<p>
<h2><%= link_to "#{post.title}", post %></h2>
</p>
<p>
  <%= truncate(post.content, length: 300) %>
</p>
<p>
  <%= link_to (image_tag post.image.url, :class => "welcome_image"), post %>
</p>
<p class="text-muted">
  <small>
     Posted on <%= post.created_at.to_formatted_s(:long) %>
  </small>  
  <small class="pull-right">
     <%= post.hearts.count %> hearts
  </small>
</p>

<br>
<br>

   <% end %>
       

app/views/posts/_form.html.erb
<%= form_for @post, html: { multipart: true } do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :title %><br>
    <%= f.text_field :title, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :content %><br>
    <%= f.text_area :content, class: "form-control" %>
  </div>

 <div class="form-group">
    <%= f.label :image %>
    <%= f.file_field :image, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.submit "Submit", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/posts/_post.html.erb
<p>
  <div class="pull-right">
    <%= form_for(Heart.new) do |f| %>
    <%= f.hidden_field :post_id, value: post.id %>
    <%= f.submit "❤", class: "btn btn-danger" %>
    <% end %>
  </div>  
  <h2><%= post.title %></h2>
</p>

<p>
  <%= simple_format post.content %>
  <br>
  <%= image_tag post.image.url, :class => "post_image" %>
</p>
  
<br>

<p class="text-muted">
  <small>
     Posted on <%= post.created_at.to_formatted_s(:long) %>
  </small>  
  <small class="pull-right">
     <%= post.hearts.count %> hearts
  </small>
</p>

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<h1>Posts</h1>

<table class="table table-hover">
  <thead>
    <tr>
      <th>Title</th>
      <th>Post</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.title %></td>
        <td><%= truncate(post.content, length: 300) %></td>
        <td><%= image_tag post.image.url, :class => "style_image" %></td>
        <% if user_signed_in? %>
        <td><%= link_to 'Show', post %></td>
        <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <td><%= link_to 'Delete', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Post', new_post_path %>

app/views/posts/new.html.erb
<h1>New post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
  <%= render "post", post: @post %>